import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { iosImportApi } from '../api/ios-import'
import Button from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import Spinner from '../components/Spinner'
import { 
  Smartphone, 
  Download, 
  Copy, 
  CheckCircle, 
  Users,
  FileText,
  Globe,
  Settings
} from 'lucide-react'

export default function IOSShortcutsGuide() {
  const navigate = useNavigate()
  const [iosImportData, setIosImportData] = useState('')
  const [isImporting, setIsImporting] = useState(false)
  const [importResult, setImportResult] = useState<{
    success: boolean
    imported: number
    duplicates: number
    message: string
  } | null>(null)

  const handleIOSImport = async () => {
    if (!iosImportData.trim()) {
      alert('Please paste the contact data from your iOS Shortcut')
      return
    }

    setIsImporting(true)
    try {
      const contacts = iosImportApi.parseShortcutsCSV(iosImportData)
      const result = await iosImportApi.importContacts({
        contacts,
        source: 'ios-shortcuts'
      })

      if (result.success) {
        setImportResult({
          success: true,
          imported: result.imported,
          duplicates: result.duplicates,
          message: result.message
        })
        
        // Auto-redirect to contacts after successful import
        setTimeout(() => {
          navigate('/contacts', { 
            state: { 
              message: `Successfully imported ${result.imported} contacts from iOS Shortcuts!`,
              importedCount: result.imported
            }
          })
        }, 3000)
      } else {
        setImportResult({
          success: false,
          imported: 0,
          duplicates: 0,
          message: result.message
        })
      }
    } catch (error) {
      console.error('iOS import error:', error)
      setImportResult({
        success: false,
        imported: 0,
        duplicates: 0,
        message: 'Error importing contacts. Please try again.'
      })
    } finally {
      setIsImporting(false)
    }
  }

  const downloadShortcutInstructions = () => {
    const instructions = `# Rhiz Contacts Export - iOS Shortcut Setup

## Quick Setup (5 minutes)

### Step 1: Create the Shortcut
1. Open the Shortcuts app on your iPhone
2. Tap the + button to create a new shortcut
3. Name it "Export Contacts to Rhiz"

### Step 2: Add Actions
Add these actions in order:

#### Action 1: Get All Contacts
- Search for "Get All Contacts"
- Tap to add it

#### Action 2: Get Details of Contacts  
- Search for "Get Details of Contacts"
- Tap to add it
- Select these properties:
  ✓ First Name
  ✓ Last Name  
  ✓ Organization
  ✓ Job Title
  ✓ Phone Numbers
  ✓ Email Addresses
  ✓ Notes

#### Action 3: Create CSV Text
- Search for "Text"
- Add this template:
\`\`\`
First Name,Last Name,Organization,Job Title,Phone,Email,Notes
{{Repeat with each in Contacts}}
{{First Name}},{{Last Name}},{{Organization}},{{Job Title}},{{Phone Numbers}},{{Email Addresses}},{{Notes}}
{{End Repeat}}
\`\`\`

#### Action 4: Copy to Clipboard
- Search for "Copy to Clipboard"
- Add it after the Text action

#### Action 5: Show Success Message
- Search for "Show Result"
- Set text to: "✅ Contacts exported! Copy the data and paste it into Rhiz."

### Step 3: Test the Shortcut
1. Tap the play button to test
2. Grant permission to access contacts when prompted
3. Check that CSV data is copied to clipboard

## Usage Instructions

### Method 1: Manual Import (Recommended)
1. Run the shortcut on your iPhone
2. Copy the CSV data from clipboard
3. Go to Rhiz → Import → iOS Shortcuts
4. Paste the data in the text area
5. Click "Import Contacts"

### Method 2: Direct Web Import (Advanced)
For automatic import, add this action after "Copy to Clipboard":
- Search for "Get Contents of URL"
- Set URL to: ${window.location.origin}/api/ios-import
- Set Method to: POST
- Add header: Content-Type: application/json
- Set Request Body to: {"contacts": {{Shortcut Input}}, "source": "ios-shortcuts"}

## Troubleshooting

### Permission Issues
- Go to Settings → Privacy & Security → Contacts
- Make sure Shortcuts has permission to access contacts

### Empty CSV
- Check that you selected the correct properties in "Get Details of Contacts"
- Make sure you have contacts in your iPhone

### Import Errors
- Verify the CSV format matches the template exactly
- Check that contact names are not empty
- Ensure at least one contact has a phone number or email

## Support
If you need help, contact support at help@rhiz.com

---
Generated by Rhiz CRM - ${new Date().toLocaleDateString()}
`

    const blob = new Blob([instructions], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'rhiz-ios-shortcut-setup.txt'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
              <Smartphone className="w-5 h-5 text-blue-600" />
            </div>
            <div>
              <h1 className="text-3xl font-bold text-gray-900">iOS Shortcuts Integration</h1>
              <p className="text-gray-600">Export your iPhone contacts directly to Rhiz</p>
            </div>
          </div>
        </div>

        {/* Setup Steps */}
        <div className="grid lg:grid-cols-2 gap-8 mb-8">
          {/* Setup Guide */}
          <Card className="p-6">
            <div className="flex items-center gap-3 mb-4">
              <Settings className="w-5 h-5 text-blue-600" />
              <h2 className="text-xl font-semibold text-gray-900">Setup Guide</h2>
            </div>
            
            <div className="space-y-4">
              <div className="bg-blue-50 p-4 rounded-lg">
                <h3 className="font-medium text-blue-900 mb-2">Quick Setup (5 minutes)</h3>
                <ol className="text-blue-800 space-y-2 text-sm">
                  <li>1. Open Shortcuts app on your iPhone</li>
                  <li>2. Create a new shortcut named "Export Contacts to Rhiz"</li>
                  <li>3. Add 5 actions: Get Contacts → Get Details → Create CSV → Copy → Show Result</li>
                  <li>4. Download the detailed instructions below</li>
                </ol>
              </div>

              <Button
                onClick={downloadShortcutInstructions}
                className="w-full"
                variant="outline"
              >
                <Download className="w-4 h-4 mr-2" />
                Download Setup Instructions
              </Button>

              <div className="text-sm text-gray-600">
                <p>📱 Works with iPhone iOS 13+</p>
                <p>🔒 Your contacts stay private - data is sent directly to Rhiz</p>
                <p>⚡ One-tap export after setup</p>
              </div>
            </div>
          </Card>

          {/* Import Area */}
          <Card className="p-6">
            <div className="flex items-center gap-3 mb-4">
              <FileText className="w-5 h-5 text-green-600" />
              <h2 className="text-xl font-semibold text-gray-900">Import Contacts</h2>
            </div>

            {!importResult ? (
              <div className="space-y-4">
                <div className="bg-green-50 p-4 rounded-lg">
                  <h3 className="font-medium text-green-900 mb-2">How to import:</h3>
                  <ol className="text-green-800 space-y-1 text-sm">
                    <li>1. Run your iOS Shortcut</li>
                    <li>2. Copy the CSV data from clipboard</li>
                    <li>3. Paste it in the text area below</li>
                    <li>4. Click "Import Contacts"</li>
                  </ol>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Paste contact data from iOS Shortcut:
                  </label>
                  <textarea
                    value={iosImportData}
                    onChange={(e) => setIosImportData(e.target.value)}
                    placeholder="Paste the CSV data from your iOS Shortcut here..."
                    className="w-full h-32 p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                  />
                </div>

                <div className="flex space-x-3">
                  <Button
                    onClick={handleIOSImport}
                    disabled={!iosImportData.trim() || isImporting}
                    className="flex-1"
                  >
                    {isImporting ? (
                      <>
                        <Spinner size="sm" />
                        Importing...
                      </>
                    ) : (
                      <>
                        <Users className="w-4 h-4 mr-2" />
                        Import Contacts
                      </>
                    )}
                  </Button>
                  <Button
                    onClick={() => setIosImportData('')}
                    variant="outline"
                  >
                    Clear
                  </Button>
                </div>
              </div>
            ) : (
              <div className="text-center py-8">
                {importResult.success ? (
                  <div className="space-y-4">
                    <CheckCircle className="w-16 h-16 text-green-500 mx-auto" />
                    <h3 className="text-xl font-semibold text-green-900">Import Successful!</h3>
                    <div className="space-y-2 text-sm text-gray-600">
                      <p>✅ {importResult.imported} contacts imported</p>
                      {importResult.duplicates > 0 && (
                        <p>⚠️ {importResult.duplicates} duplicates skipped</p>
                      )}
                    </div>
                    <p className="text-sm text-gray-500">
                      Redirecting to contacts page...
                    </p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto">
                      <span className="text-red-600 text-2xl">!</span>
                    </div>
                    <h3 className="text-xl font-semibold text-red-900">Import Failed</h3>
                    <p className="text-sm text-gray-600">{importResult.message}</p>
                    <Button
                      onClick={() => setImportResult(null)}
                      variant="outline"
                    >
                      Try Again
                    </Button>
                  </div>
                )}
              </div>
            )}
          </Card>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          <Card className="p-6 text-center">
            <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mx-auto mb-4">
              <Smartphone className="w-6 h-6 text-blue-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Native iPhone Integration</h3>
            <p className="text-gray-600">Works seamlessly with iOS Shortcuts - feels like a native app feature</p>
          </Card>

          <Card className="p-6 text-center">
            <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mx-auto mb-4">
              <Copy className="w-6 h-6 text-green-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">One-Tap Export</h3>
            <p className="text-gray-600">Export all your contacts with a single tap after initial setup</p>
          </Card>

          <Card className="p-6 text-center">
            <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mx-auto mb-4">
              <Globe className="w-6 h-6 text-purple-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Smart Field Mapping</h3>
            <p className="text-gray-600">Automatically maps Apple contact fields to Rhiz format</p>
          </Card>
        </div>

        {/* Alternative Methods */}
        <Card className="p-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">Other Import Methods</h2>
          <div className="grid md:grid-cols-2 gap-4">
            <Button
              onClick={() => navigate('/import')}
              variant="outline"
              className="justify-start"
            >
              <FileText className="w-4 h-4 mr-2" />
              CSV Upload
            </Button>
            <Button
              onClick={() => navigate('/settings')}
              variant="outline"
              className="justify-start"
            >
              <Globe className="w-4 h-4 mr-2" />
              Google Contacts Sync
            </Button>
          </div>
        </Card>
      </div>
    </div>
  )
} 